#define MICROPY_HW_BOARD_NAME "VCC-GND Studio YD RP2040"
#define MICROPY_HW_MCU_NAME "rp2040"

#define CIRCUITPY_CONSOLE_UART_TX (&pin_GPIO1)
#define CIRCUITPY_CONSOLE_UART_RX (&pin_GPIO0)

#define MICROPY_HW_NEOPIXEL (&pin_GPIO23)
